// The Dart cleaner must give exactly the same result as app/deid.py on the
// parity corpus (test/data/deid_parity.json, generated by tool/deid_parity.py).
import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:your_counselor/core/deid/cleaner.dart';

void main() {
  final data = jsonDecode(File('test/data/deid_parity.json').readAsStringSync()) as Map<String, dynamic>;
  final cases = (data['cases'] as List).cast<Map<String, dynamic>>();

  for (final (i, c) in cases.indexed) {
    test('case $i matches the Python cleaner', () {
      final r = clean(c['text'] as String);
      expect(r.text, c['cleaned'], reason: 'cleaned text differs');
      expect(r.redactions.map((x) => x.type).toList(), c['types'], reason: 'redaction types differ');
      expect(r.warnings, c['warnings'], reason: 'possible-name warnings differ');
    });
  }
}
