/// On-device de-identification "cleaner": a Dart port of `app/deid.py`.
///
/// Product rule (hard, not a hope): no names, phone numbers, emails, addresses,
/// ID numbers, employer/school names, or rare identifying details may leave the
/// clinician's phone. Age, sex, symptoms, history and scores are fine.
///
/// `app/deid.py` is the reference implementation. This port must:
///   * pass every vector in `fixtures/deid_vectors.json`
///     (test/deid_vectors_test.dart), and
///   * produce the same output as the Python cleaner on the parity corpus
///     (test/deid_parity_test.dart, regenerated by tool/deid_parity.py).
///
/// The server runs the Python cleaner again on every request and rejects the
/// text if it finds anything, so this port is the first line of defence, not
/// the only one. Dart's regex engine is ASCII-only for `\w`, `\d` and `\b`,
/// where Python's is Unicode; the server re-check covers that gap.
///
/// SAFETY FILE: changes need the `clinician-reviewed` label (see CLAUDE.md).
/// Never weaken a pattern to make something pass: add a failing vector first.
library;

const _honorifics = r'(?:Mr|Mrs|Ms|Miss|Mx|Dr|Prof|Shri|Shrimati|Smt|Sri|Sh|Kumari|Km|Master|Baby|Late)';
const _cap = r'[A-Z][a-z]+';
const _nameTail = '$_cap(?:\\s+$_cap){0,2}';

RegExp _ci(String pattern) => RegExp(pattern, caseSensitive: false);

/// Order matters: earlier categories win overlapping spans.
final List<(String, RegExp)> _patterns = [
  ('EMAIL', RegExp(r'\b[\w.+-]+@[\w-]+(?:\.[\w-]+)+\b')),
  ('URL', _ci(r'\b(?:https?://|www\.)\S+')),
  ('HANDLE', RegExp(r'(?<![\w@])@[A-Za-z0-9_.]{3,}')),
  // Labelled identifiers: "Aadhaar: 1234 5678 9012", "UHID 44321", "MRN-9981"
  (
    'ID',
    _ci(
      r'\b(?:aadhaa?r|uid|uhid|mrn|ipd|opd|reg(?:istration)?\.?\s*no|roll\s*no|'
      r'employee\s*id|emp\s*id|pan\s*(?:card|no)|passport|voter\s*id|abha|ration\s*card|'
      r'policy\s*no|account\s*no)\b\.?\s*(?:no\.?|number|#)?\s*[:\-]?\s*(?=[A-Z0-9\-/ ]*\d)[A-Z0-9][A-Z0-9\-/ ]{3,20}[A-Z0-9]',
    ),
  ),
  (
    'DOB',
    _ci(
      r'\b(?:d\.?o\.?b\.?|date\s+of\s+birth|born\s+on)\s*[:\-]?\s*'
      r'(?:\d{1,2}[\-/. ]\d{1,2}[\-/. ]\d{2,4}|\d{1,2}\s+[A-Za-z]{3,9}\s+\d{4}|[A-Za-z]{3,9}\s+\d{1,2},?\s+\d{4})',
    ),
  ),
  ('ID', RegExp(r'\b[A-Z]{5}\d{4}[A-Z]\b')), // PAN
  ('ID', RegExp(r'\b[A-Z]{3}\d{7}\b')), // Voter ID (EPIC)
  ('ID', RegExp(r'\b[A-PR-WY][1-9]\d\s?\d{4}[1-9]\b')), // Passport
  ('ID', RegExp(r'\b[2-9]\d{3}[\s-]\d{4}[\s-]\d{4}\b')), // Aadhaar, spaced
  // Indian mobile: optional +91 / 91 / 0, then 10 digits starting 6-9
  ('PHONE', RegExp(r'(?<!\d)(?:\+?91[\s-]?|0)?[6-9]\d{4}[\s-]?\d{5}(?!\d)')),
  // Landline with STD code: 020-2345 6789, 022 23456789
  ('PHONE', RegExp(r'(?<!\d)0\d{2,4}[\s-]\d{3,4}[\s-]?\d{4}(?!\d)')),
  (
    'ADDRESS',
    _ci(
      r'\b(?:resides?\s+at|residing\s+at|lives\s+at|living\s+at|address\s*[:\-]|'
      r'r/o|staying\s+at)\s*[^.\n]{3,120}',
    ),
  ),
  (
    'ADDRESS',
    _ci(
      r'\b(?:flat|house|h\.?\s?no|plot|room|door|bldg|building|wing|block)\s*(?:no\.?|number|#)?\s*[:\-]?\s*'
      r'[A-Z]?\d{1,5}[A-Z]?\b[^.\n]{0,80}',
    ),
  ),
  ('PINCODE', _ci(r'\b(?:pin(?:\s*code)?|pincode|postal\s*code)\s*[:\-]?\s*[1-9]\d{2}\s?\d{3}\b')),
  // Honorific + capitalised name
  ('NAME', RegExp('\\b$_honorifics\\.?\\s+$_nameTail')),
  // "name is X", "named X", "Name: X", "called X" (capitalised only)
  ('NAME', RegExp('\\b(?:[Nn]ame\\s*(?:is|:|-)|[Nn]amed|goes\\s+by|[Cc]alled)\\s+$_nameTail')),
  // Employer / school / college with a capitalised proper name
  (
    'ORG',
    RegExp(
      r'\b(?:works?\s+(?:at|in|for|with)|working\s+(?:at|in|for|with)|employed\s+(?:at|in|by|with)|'
      r'job\s+at|studies\s+at|studying\s+(?:at|in)|student\s+(?:at|of)|enrolled\s+(?:at|in)|'
      r'school\s*[:\-]|college\s*[:\-]|company\s*[:\-]|employer\s*[:\-])\s+(?:the\s+)?'
      r'(?!(?:IT|BPO|KPO|MNC|PSU|ITES|Govt|Government|Private|Pvt|Sales|Marketing|HR|Finance|Accounts|Education|Healthcare|Hospitality|Retail|Construction|Agriculture)\b)'
      r"[A-Z][\w&.'-]*(?:\s+[A-Z][\w&.'-]*){0,4}",
    ),
  ),
  // Any other long digit run (≥7 digits, spaces/hyphens allowed): account, MRN…
  ('ID', RegExp(r'(?<![\d/.-])\d(?:[\s-]?\d){6,}(?![\d/.-])')),
];

/// Numbers that must never be redacted (crisis lines from crisis-resources.md).
const _protectedLiterals = ['1-800-891-4416', '1800-891-4416', '18008914416'];

/// Dates are kept (session dates, onset dates) unless labelled as DOB.
final _date = RegExp(r'\b\d{1,4}[\-/.]\d{1,2}[\-/.]\d{1,4}\b');

// Python's `\b` treats accented letters as word characters; Dart's does not,
// so the word end is spelled out to match app/deid.py ("José" is not "Jos").
final _possibleName = RegExp(r'(?<=[a-z0-9,;:)]\s)([A-Z][a-z]{2,})(?![\p{L}\p{N}_])', unicode: true);

final Set<String> _commonTitleCase = {
  // calendar
  ...'monday tuesday wednesday thursday friday saturday sunday'.split(' '),
  ...'january february march april may june july august september october november december'.split(' '),
  // languages, religions, regions (coarse location is allowed)
  ...'hindi marathi english gujarati tamil telugu kannada malayalam bengali punjabi urdu odia assamese konkani'.split(
    ' ',
  ),
  ...'hindu muslim christian sikh jain buddhist parsi islam christianity god allah bhagwan diwali eid holi christmas navratri ramadan'
      .split(' '),
  ...'india indian maharashtra mumbai pune delhi bangalore bengaluru chennai hyderabad kolkata nagpur nashik thane goa gujarat karnataka kerala'
      .split(' '),
  // clinical / system words that commonly appear capitalised mid-sentence
  ...'client patient mother father sister brother wife husband son daughter grandmother grandfather aunt uncle'.split(
    ' ',
  ),
  ...'cbt erp dbt act emdr mse gad phq dass ham rses icd dsm who ayurvedic homeopathic unani yoga pranayama'.split(' '),
  ...'tele tele-manas manas child women helpline emergency section mode week session'.split(' '),
  ...'i ok no yes not he she they his her their'.split(' '),
};

class Redaction {
  const Redaction(this.type, this.start, this.end);

  /// EMAIL, URL, HANDLE, ID, DOB, PHONE, ADDRESS, PINCODE, NAME or ORG.
  final String type;
  final int start;
  final int end;

  String get replacement => '[$type]';
}

class CleanResult {
  const CleanResult({required this.text, required this.redactions, required this.warnings});

  /// Cleaned text, safe to send.
  final String text;
  final List<Redaction> redactions;

  /// Capitalised words that might be a person's name, for the clinician to review.
  final List<String> warnings;

  /// Counts by type only; never the values.
  Map<String, int> get counts {
    final out = <String, int>{};
    for (final r in redactions) {
      out[r.type] = (out[r.type] ?? 0) + 1;
    }
    return out;
  }

  bool get isClean => redactions.isEmpty;
}

bool _overlaps((int, int) a, List<(int, int)> spans) => spans.any((s) => a.$1 < s.$2 && s.$1 < a.$2);

List<(int, int)> _protectedSpans(String text) {
  final spans = <(int, int)>[];
  for (final lit in _protectedLiterals) {
    var i = text.indexOf(lit);
    while (i >= 0) {
      spans.add((i, i + lit.length));
      i = text.indexOf(lit, i + lit.length);
    }
  }
  for (final m in _date.allMatches(text)) {
    spans.add((m.start, m.end));
  }
  return spans;
}

List<Redaction> findIdentifiers(String text) {
  final protected = _protectedSpans(text);
  final taken = <(int, int)>[];
  final found = <Redaction>[];
  for (final (kind, pattern) in _patterns) {
    for (final m in pattern.allMatches(text)) {
      final span = (m.start, m.end);
      // Labelled DOB overrides date protection; everything else respects it.
      if (kind != 'DOB' && _overlaps(span, protected)) continue;
      if (_overlaps(span, taken)) continue;
      taken.add(span);
      found.add(Redaction(kind, m.start, m.end));
    }
  }
  // Spans never overlap, so starts are unique and the order is total.
  found.sort((a, b) => a.start.compareTo(b.start));
  return found;
}

/// Title-case words that are not at a sentence start and not common words.
List<String> possibleNames(String text) {
  final hits = <String>[];
  for (final m in _possibleName.allMatches(text)) {
    final w = m.group(1)!;
    if (_commonTitleCase.contains(w.toLowerCase())) continue;
    if (!hits.contains(w)) hits.add(w);
  }
  return hits;
}

CleanResult clean(String text) {
  final reds = findIdentifiers(text);
  final out = StringBuffer();
  var last = 0;
  for (final r in reds) {
    out
      ..write(text.substring(last, r.start))
      ..write(r.replacement);
    last = r.end;
  }
  out.write(text.substring(last));
  final cleaned = out.toString();
  return CleanResult(text: cleaned, redactions: reds, warnings: possibleNames(cleaned));
}

/// Replaces every whole-word occurrence of [name] with `[NAME]`, for a
/// possible name the clinician chose to remove.
String removeName(String text, String name) =>
    text.replaceAll(RegExp('(?<![A-Za-z])${RegExp.escape(name)}(?![A-Za-z])'), '[NAME]');
