"""
Writes mobile/test/data/deid_parity.json: the Python reference cleaner's exact
output (cleaned text, redaction types in order, possible-name warnings) for
every shared vector plus the extra cases below. test/deid_parity_test.dart
requires the Dart port to match it character for character.

  python3 mobile/tool/deid_parity.py           # regenerate after changing app/deid.py or the vectors
  python3 mobile/tool/deid_parity.py --check   # CI: fail if the file is out of date

Run from the repository root. Stdlib only.
"""
from __future__ import annotations

import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))

from app.deid import clean  # noqa: E402

OUT = ROOT / "mobile" / "test" / "data" / "deid_parity.json"

# Realistic mixed cases beyond the vectors. Add, never remove.
EXTRA = [
    "Priya, 34F, panic attacks for 3 months, 2–3 per week, fear of dying during episodes. "
    "Call 98765 43210. Works at Sunrise Traders. Came with her sister Asha. "
    "PHQ-9 8, GAD-7 14. Risk asked, denies suicidal ideation and self-harm.",
    "Mr. Anil Kumar Deshpande, 52M, lives at Flat 12B, Shanti Nagar, Pune. DOB: 12/03/1972.",
    "Email me at dr.rao+clinic@hospital.co.in or see www.example.org/profile, handle @calm_mind_22.",
    "Tele-MANAS 14416 and 1-800-891-4416 given. Session on 14/09/2026. Fees Rs 1500.",
    "Aadhaar: 2345 6789 0123, PAN ABCDE1234F, voter id ABC1234567, passport K1234567.",
    "She studies at St. Xavier's College and works for the IT sector part time.",
    "Named Rohan by his parents; goes by Ro. Called Meera Iyer at the clinic.",
    "Landline 022 2345 6789, pin code 411 001, UHID 4471923, MRN-99812.",
    "Client came with Kavya and Arjun, her cousins, on Monday in Mumbai.",
    "Account no 123456789012 was mentioned; also 98 76 54 32 10 in notes.",
    "Born on 5 March 1990. Onset 2024-01-15. Scores: HAM-A 22, DASS-21 D 18.",
    "Works at the Reserve Bank of India branch office. Employed by Tata Motors earlier.",
    "Late Shri Ramesh Gupta was her father. Smt. Lata Gupta accompanies her.",
    "résumé mentions José García; mobile +91-9123456789.",
    "No identifiers here: 28F, low mood for 6 weeks, sleep 4 hours, appetite reduced.",
    # Known gap in app/deid.py (reported, awaiting clinician-reviewed fix): the ORG rule only
    # matches lowercase "works at", so a sentence-initial "Works at X" is flagged as possible
    # names but not redacted. Kept here so both cleaners change together.
    "Works at Sunrise Traders since 2019. Studies at Fergusson College.",
    "Ms. Priya Nair, 34F, panic attacks for 3 months. Call 98765 43210. She works at Sunrise Traders.",
]


def build() -> dict:
    vectors = json.loads((ROOT / "fixtures" / "deid_vectors.json").read_text())
    texts = [v["text"] for v in vectors["must_redact"] + vectors["must_keep"]] + EXTRA
    cases = []
    for t in texts:
        r = clean(t)
        cases.append({"text": t, "cleaned": r.text, "types": [x.type for x in r.redactions], "warnings": r.warnings})
    return {
        "_about": "Generated by mobile/tool/deid_parity.py from app/deid.py. Do not edit by hand.",
        "cases": cases,
    }


def main() -> int:
    rendered = json.dumps(build(), ensure_ascii=False, indent=1) + "\n"
    if "--check" in sys.argv:
        if not OUT.exists() or OUT.read_text() != rendered:
            print("mobile/test/data/deid_parity.json is out of date: run python3 mobile/tool/deid_parity.py")
            return 1
        print("deid parity file up to date")
        return 0
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(rendered)
    print(f"wrote {OUT.relative_to(ROOT)} ({len(build()['cases'])} cases)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
